
using System.Collections.Generic;

namespace RotMG.Game.Entities
{
    public partial class Player
    {
        public static List<string> greenUtItems = new List<string>()
        {
            "Demon Blade",
            "Crystal Wand",
            "Wand of the Bulwark",
            "Dirk of Cronus",
            "Doom Bow",
            "Penetrating Blast Spell",
            "Seal of Blasphemous Prayer",
            "Cloak of the Planewalker",
            "Quiver of Thunder",
            "Staff of Extreme Prejudice",
            "Wine Cellar Incantation",
            "Robe of the Tlatoani",
            "Staff of the Crystal Serpent",
            "Cracked Crystal Skull",
            "Crystal Bone Ring",
            "Tome of Purification",
            "Celestial Blade",
            "Candy-Coated Armor",
            "Forest Giant Slayer",
            "Kendo 'Stick'",
            "Great Fang",
            "Sturdy Pegleg",
            "Theurgy Wand",
            "Giant Claw Blade",
            "Curious Eyeball",
            "Spectral Gown",
            "Crumbling Construct",
            "Garment of Medusa",
            "Captured Ritual Flame of Doom",
            "Drake's Dialect",
            "Wooden Prism",
            "Throwing Dart",
            "The War Path",
            "Head of the Cyclops King",
            "Cyclops Mace",
            "Abyssal Emblem",
            "Gilded Sword",
            "Soulless Robe",
            "Ring of the Covetous Heart",
            "Soul of the Bearer",
            "The Phylactery",
            "Bracelet of the Sprites",
            "Corporeal Shield",
            "Fishing Rod",
            "Visceration Flail",
            "Ball of Gel",
            "Drake Scale Hat",
            "Wand of Deep Nature",
            "Hooked Dagger",
            "Arcane Shiv",
            "Box of Magic",
            "Overgrowth Helmet",
        };

        public static List<string> blueRtItems = new List<string>()
        {
            "Ancient Stone Sword",
            "Shield of Ogmur",
            "Helm of the Juggernaut",
            "Orb of Conflict",
            "Conducting Wand",
            "Sanguine Femur",
            "Reaper's Wit",
            "Crypt Keeper's Crossbow",
            "Mini Brain Orb",
            "Captured Ritual Flame",
            "Spear of the Storm",
            "Soul of the Lost Land",
            "Amulet of Ancient Power",
            "Ancient Skull",
            "Ancient Crown",
            "Loins of the Cyclops God",
            "The Horned Circlet",
            "Exuberant Heavy Plate",
            "Book of Shaitan",
            "Piercing Fire",
            "Stheno's Scourge",
            "Snakeskin Guard",
            "Ophidian Gem",
            "Serpentine Guise",
            "Mithril Sword",
            "Trap of the Vile Spirit",
            "Viral Egg",
            "Will of the Den",
            "Arachnid Garment",
            "Abrupt End",
            "Twilight Truncheon",
            "Decrepit Cranium",
            "Reaper's Regalia",
            "Midnight Malice",
            "Arachnid Miasma",
            "Realm Equipment Crystal",
            "Electric Shock",
            "Purple Pea Shooter",
            "Pixie-Enchanted Sword",
            "Seal of the Enchanted Forest",
            "Fairy Plate",
            "Etherite Dagger",
            "Leaf Bow",
            "Earth's Remembrance",
            "Piss Jar",
            "The Great Lizard",
            "Bow of Blinding Heat",
            "Wand of Purified Flame",
            "Bow of War",
            "The Red Shield",
            "Rusted Helm",
            "Spell of Kinetic Projection",
            "Carved Golem Remains",
            "Brain of the Golem",
            "Golem Garments",
            "Rusty Cuffs",
        };
    }
}
