
using System.Collections.Generic;

namespace RotMG.Game.Entities
{
    public partial class Player
    {
        public static List<string> greenUtItems = new List<string>()
        {
            "Demon Blade",
            "Crystal Wand",
            "Wand of the Bulwark",
            "Dirk of Cronus",
            "Doom Bow",
            "Penetrating Blast Spell",
            "Seal of Blasphemous Prayer",
            "Cloak of the Planewalker",
            "Quiver of Thunder",
            "Staff of Extreme Prejudice",
            "Wine Cellar Incantation",
            "Robe of the Tlatoani",
            "Staff of the Crystal Serpent",
            "Cracked Crystal Skull",
            "Crystal Bone Ring",
            "Tome of Purification",
            "Celestial Blade",
            "Candy-Coated Armor",
            "Forest Giant Slayer",
            "Kendo 'Stick'",
            "Great Fang",
            "Sturdy Pegleg",
            "Theurgy Wand",
            "Giant Claw Blade",
            "Curious Eyeball",
            "Spectral Gown",
            "Crumbling Construct",
            "Garment of Medusa",
            "Drake's Dialect",
            "Wooden Prism",
            "Throwing Dart",
            "The War Path",
            "Head of the Cyclops King",
            "Cyclops Mace",
            "Abyssal Emblem",
            "Gilded Sword",
            "Soulless Robe",
            "Ring of the Covetous Heart",
            "Soul of the Bearer",
            "The Phylactery",
            "Bracelet of the Sprites",
            "Corporeal Shield",
            "Fishing Rod",
            "Visceration Flail",
            "Ball of Gel",
            "Drake Scale Hat",
            "Wand of Deep Nature",
            //"Hooked Dagger",
            "Arcane Shiv",
            "Box of Magic",
            "Overgrowth Helmet",
        };

        public static List<string> blueRtItems = new List<string>()
        {
            "Ancient Stone Sword",
            "Shield of Ogmur",
            "Helm of the Juggernaut",
            "Orb of Conflict",
            "Conducting Wand",
            "Sanguine Femur",
            "Reaper's Wit",
            "Crypt Keeper's Crossbow",
            "Mini Brain Orb",
            "Captured Ritual Flame",
            "Spear of the Storm",
            "Soul of the Lost Land",
            "Amulet of Ancient Power",
            "Ancient Skull",
            "Ancient Crown",
            "Loins of the Cyclops God",
            "The Horned Circlet",
            "Exuberant Heavy Plate",
            "Book of Shaitan",
            "Piercing Fire",
            "Stheno's Scourge",
            "Snakeskin Guard",
            "Ophidian Gem",
            "Serpentine Guise",
            "Mithril Sword",
            "Trap of the Vile Spirit",
            "Viral Egg",
            "Will of the Den",
            "Arachnid Garment",
            "Abrupt End",
            "Twilight Truncheon",
            "Decrepit Cranium",
            "Reaper's Regalia",
            "Midnight Malice",
            "Arachnid Miasma",
            //"Realm Equipment Crystal",
            "Electric Shock",
            "Purple Pea Shooter",
            "Pixie-Enchanted Sword",
            "Seal of the Enchanted Forest",
            "Fairy Plate",
            "Etherite Dagger",
            "Leaf Bow",
            "Earth's Remembrance",
            "Piss Jar",
            "The Great Lizard",
            "Bow of Blinding Heat",
            "Wand of Purified Flame",
            "Bow of War",
            "The Red Shield",
            "Rusted Helm",
            "Spell of Kinetic Projection",
            "Carved Golem Remains",
            "Brain of the Golem",
            "Golem Garments",
            "Rusty Cuffs",
        };

        public static List<string> eventEggItems = new List<string>()
        {
            "Lesser Fiery Equipment Crystal",
            "Lesser Ghastly Equipment Crystal",
            "Oryx Equipment Crystal",
        };

        public static List<string> legendaryTransformation = new List<string>()
        {
            "Ring of the Sphinx",
            "Ring of the Nile",
            "Ring of the Pyramid",
            "Tome of Holy Protection",
            "Ring of Divine Faith",
            "Piece of Havoc",
            "Destruction Invoker",
            "Unholy Robe",
            "Tome of UNHoly Guidance",
            "Amulet of Backwards Luck",
            "Bow of Life Energy",
            "Reinforced Ribcage",
            "Boshy Gun",
            "Staff of Godes",
            "Horned Suguyari",
            "Seal of Havoc",
            "The Molten Cape",
            "Scarlet's Power",
            "Haunted Silo",
            "Dominion of the Dragon",
            "Oryx Equipment Crystal",
            "Sword of Heroic Flame",
            "Pendant of Thunder",
            "Hide of Undead Regeneration",
            "Robe of Pure Madness",
            "Fiery Equipment Crystal",
            "Ghastly Equipment Crystal",
            "Orb of Undeniable Insight",
            "Arched Dagger",
            "Cloak of the Timeless",
            "King of the Jellyfish",
            "Sand Monster Contract",
            "Hero's Garb",
            "Paladin's Waraxe",
            "Upgrading Equipment Crystal",
            "Cosmic Cloak",
            "Soul of Havoc",
            "Helm of the Watcher",
            "Marble Seal",
            "Breastplate of New Life",
            "Magical Lodestone",
            "Cloak of Bloody Surprises",
            "Sapphire Sword",
            "Defender Sword",
            "Shaderunner Cloak",
            "Thunder and Lightning",
            "Viperstring",
            "Blade of Thorns",
            "Rose Petal Amulet",
            "Rose Petal Staff",
            "Skull of Lenin",
            "Amulet of Granithia",
            "Granithia's Garments",
            "Stone-Forged Spear",
            "Granithia's Blaster",
            "Shade of the Phoenix",
            "Blade of the Angel's Honor",
            "Poseidon's Gauntlet",
            "Larry Gun",
            "Gratuitous Gift",
            "Steel-Woven Hide",
            "Soul's Guidance",
            "Steel-Woven Hide",
            "Herculean Amulet",
            "Royal Dagger",
            "Aegis of the Devourer",
            "Platemail of the Stalwart",
            "Lance of Honour",
            "The Monarch's Grasp",
            "Plate of the Beast",
            "Piercing Silence",
            "The Ultimatum",
            "Rip of Soul",
            "Wand of Violent Mana",
            "Sincryer's Demise",
            "Amulet of Oryx",
            "Flash-Fire",
            "An Alien's Blessing",
            "Dagger of Dark Descent",
            "Tormentor of the Deep",
            "Eradication Bow",
            "Sword of Elegance",
            "The Odyssey",
            "Burden of the Warpawn",
            "Wand of Divine Lightning",
            "Scutum of the Legionnaire",
            "Split-Shot Crossbow",
            "Unknown Unstable Ballista",
            "Enchanted Leather Hide",
            "The Ranger?s Grace",
            "Soulshredder",
            "Judgement's Call",
            "Gem of True Eminence",
            "Heater of Union",
            "Cloth of the Battle-Mage",
            "Jackpot",
            "Band of Exoneration",
            "Grasp of Elysium",
            "The Executioner",
            "The Storm Blanket",
            "Protective Psalm",
            "Bloodstar",
            "Evanescence",
            "Stride of the Multitude",
            "Scepter of the Other",
            "Detrimental Destiny",
            "Immunity Gauntlet",
            "Khonsu's Breastplate",
            "Spell of 1000 Strikes",
            "Scarlet Battle-Axe",
            "Overlord's Crown",
            "Grand Curse",
            "Never Before Seen",
            "Psychotic Attacks",
            "The Bewildering",
            "Bolstered Helm",
            "The Kingdom's Pride",
            "Skull of the Titan",
            "Time-Worn Redeemer",
            "Skull of Dark Spirits",
            "Whispers from Beyond",
            "Purity's Call",
            "Kunai",
            "Book of Burning Souls",
            "Sheath of True Past",
            "Ring of Misfortune",
            "Sky-Striker",
            "Volcanic Vengeance",
            "Path to the Underworld",
            "Ascension",
            "Interstellar Force",
            "Death's Vow",
            "Grace of the Colossus",
            "Prism of Mirrors",
            "Eternal Deficit",
            "The Master's Betrayal",
            "Drannol's Fury",
            "Fortification Shield",
            "Blades of Denial",
            "Infused Spike",
            "Beastly Remains",
            "Inferno of Truth",
            "Blood-Fang",
            "Banner of Immense Protection",
            "Lance of Immense Protection",
            "Infused Katana",
            "Demonic Resonance",
            "Never Ending Nightmare",
            "The ET Experience",
            "Told Before Time",
            "Mad Jester Egg",
            "Leaf Dragon Hide Armor",
            "Water Dragon Silk Robe",
            "Fire Dragon Battle Armor",
            "Doku No Ken",
            "Tablet of the King's Avatar",
            "Kepi of Uncontrollable Darkness",
            "Bow of the Morning Star",
            "Sword of Illumination",
            "Precisely Calibrated Stringstick",
            "Harlequin Armor",
            "Staff of Esben",
            "Skullish Remains of Esben",
            "Ring of Pure Wishes",
            "Cloak of Total Madness",
            "Soulreaper Armor",
            "Wand of Electric",
            "Pulse Scepter of Zeus",
            "Darkness Rise Armor",
            "Wand of Elemental Sanctuary",
            "Elemental Relic",
            "Elemental Tome",
            "Riotracatry Robe",
            "Dagger of Unearthly Storms",
            "Deathwanderer",
            "Titan Blood Armor",
            "Wildfire Crossbow",
            "Tundracian Frozen Armor",
            "Sword of the Archpaladin",
            "Scutum of the Legionnaire",
            "Holy Breastplate",
            "Menacing Sword of No Escape",
            "Blue Tunic",
            "Cloak of Vivacity",
            "Genisus Dagger",
            "Bastion of Wrath",
            "Doge's Sharp Swagger Star",
            "Infused Spike",
            "Null-Magic Trap",
            "Secretive Phial",
            "Helm of the Macrotitans",
            "Earthsunder Hammer",
            "Ogreclub",
            "Cheval Trap Dagger",
            "Armor of the Iron Golem",
            "Cyclops' Eye",
            "Hellslicer",
            "Ghilact Dagger",
            "Fairy Blade",
            "Bow of Dreadful Reign",
            "Nether Blade",
            "Ring of the Wildfire",
            "Stormbreaker",
            "Bow of Ornias",
            "Fun Hat",
            "Springed Boxing Glove",
            "Spell of Sorrow",
            "Nimbus Scepter",
            "Frost Wand",
            "Bow of Lost Promises",
            "Eternity Armor",
            "Ivory Ring",
            "Prototype Scepter v01",
            "Prototype Wand v01",
            "Lotus Star",
            "Skycrusher Trap",
            "Rally of the Dreadnought",
            "Lorespire Robe",
            "Adroit Armor",
            "Sheath of the Holy Revival",
            "Spectrum Robe",
            "Blade of Offerings",
            "Cultist Armor",
            "Mysterious Stone",
            "Shield of the Phantom",
            "Staff of the Golden Gate",
            "Quiver of Distortion",
            "Farewell Armor",
            "Wand of Goo",
            "Staff of the Hilarious Jester",
            "Ring of Undeadly Conjury",
            "Olden Necromancy Cloth",
            "Sword of Fierce Force",
            "Ultimate Nunchucks",
            "Black Belt",
            "Sky Tome",
            "Fate Wand",
            "Redshade Shield",
            "Swiftsword",
            "Royalty Armor",
            "Noble Heatblast Trap",
            "Royalty Ring",
            "Mirror Dagger",
            "Phenomenon Disc",
            "Staff of Indecisive Maneuvers",
            "Blueshade Shield",
            "Flamebred Robe",
            "Robe of Overgrowth",
            "Blackguard Seal",
            "Wand of Obscurity",
            "Skull Helm",
            "Beastly Remains",
            "Sword of Dark Retribution",
            "Helm of Dark Retribution",
            "Armo of Dark Retribution",
            "Ring of Dark Retribution",
            "Split-Shot Crossbow",
            "Robe of Wrath",
            "Katana of Mythical Alliance",
            "Ring of Scarred Dreams",
            "Dagger of Dark Descent",
            "Tormentor of the Deep",
            "Eradication Bow",
            "Sword of Elegance",
            "Overlord's Crown",
            "Platemail of the Stalwart",
            "Spirit of the Heart",
            "Pork Killer",
            "Fatefixer Star",
            "The ET Experience",
            "The Odyssey",
            "Solace and Calamity",
            "Detrimental Destiny",
            "Bow of the Spider Silk",
            "Spider Web Trap",
            "Grasp of Elysium",
            "The Executioner",
            "The Ultimatum",
            "Rip of Soul",
            "Imprecation Upon Us",
            "Unlimited AK47",
            "Steel-Woven Hide",
            "The Bewildering",
            "Stinger Spell",
            "Soulshredder",
            "Winged Wasp Armor",
            "The Bees Knees",
            "Bow of the Lonesome Wraith",
            "Purity's Call",
            "Exanimation Stone",
            "Dirk of Benevolence",
            "Extermination",
            "Mind over Matter",
            "Never Before Seen",
            "Swiss Army Knife",
            "Bloodstar",
            "Xion Charge",
            "The Storm Blanket",
            "Protective Psalm",
            "Blessing of Asclepius",
            "Judgement's Call",
            "Gem of True Eminence",
            "Living Corrupted Ambition",
            "Remorse of Murak'ul",
            "Dark Land Ruination",
            "Ieastorian Armor",
            "The ET Experience",
            "Surge Cloak",
            "V-X Spark Armor",
            "Spell of 1000 Strikes",
            "Burden of the Warpawn",
            "Broadsword of Bloodshed",
            "Evil Shield of the Dark Knight",
            "Chestguard of the Underworld",
            "Amulet of the Dark Knight",
            "Staff of BLAH",
            "Katana of the Vicious Plot",
            "Ring of the Hidden Temple",
            "Stride of the Multitude",
            "Godslayer Sword",
            "Spacesuit",
            "Space Helm",
            "Sinburn Hide",
            "Void Blade",
            "The Ranger's Grace",
            "The Eye of Peril",
            "Skull of Hades",
            "Truncheon of Immortal Demons",
            "Coat of the Devil",
            "Magic Throwing Cards",
            "Dagger of Corruption",
            "Shadow Beacon",
            "Wand Of The Prohibited Fire",
            "Siphon of Courage",
            "Banner of the Blood Mountains",
            "God Blood Robes",
            "Earthbound Lance",
            "The Realmtracer",
            "Staff of Dark Malediction",
            "Funnystone",
            "Gratuitous Gift",
            "An Alien's Blessing",
            "Forsaken Shield",
            "Scepter of the Other",
            "Wand of Violent Mana",
            "Sincryer's Demise",
            "Grace of the Colossus",
            "Lance of the Terrorshrine",
            "Wand of Violent Mana",
            "Tome of Crimson Writings",
            "Eradication Wand",
            "Path to the Underworld",
            "Mythical Basilisk Venom",
            "Time-Worn Redeemer",
            "Necromantic Charm",
            "Ring of Fortune",
            "Razzmatazz Armor",
            "Night Dice",
            "Dagger of Demon Sacrifice",
            "Ring of the Storm Gods",
            "Typhoon Wand",
            "Platinum Dretix",
            "Death Necklace",
            "Skull of Dark Spirits",
            "Scarlet Battle-Axe",
            "Armor of Resilience",
            "Herculean Amulet",
            "Royal Dagger",
            "Aegis of the Devourer",
            "Wand of Divine Lightning",
            "Khonsu's Breastplate",
            "Asteroid",
            "The Monarch's Grasp",
            "Plate of the Beast",
            "Piercing Silence",
            "Bolstered Helm",
            "Flash-Fire",
            "Unknown Unstable Ballista",
            "Enchanted Leather Hide",
            "Cloth of the Battle-Mage",
            "Heater of Union",
            "Poseidon's Will",
            "Evanescence",
            "Immunity Gauntlet",
            "Grand Curse",
            "Psychotic Attacks",
            "The Kingdom's Pride",
            "Soul's Guidance",
            "Flashburst Spell",
            "Ascendant Quiver",
            "Marble Tablet",
            "The Untameable",
            "Whispers from Beyond",
            "Ancient Stone Maul",
            "Dreamweaver of Darogek",
            "Treacherous Venom",
            "Kunai",
            "Book of Burning Souls",
            "Sheath of True Past",
            "Ring of Misfortune",
            "Abyssal Whip",
            "Sky-Striker",
            "Volcanic Vengeance",
            "Ascension",
            "Interstellar Force",
            "Death's Vow",
            "Prism of Mirrors",
            "Jacket of True Darkness",
            "Otherworldly Blades",
            "Eternal Deficit",
            "Banner of the Furious Kraken",
            "Truestone Ring",
            "The Master's Betrayal",
            "Royalty Bow",
            "Evisceration Claws",
            "The Twisted Cloak",
            "Drannol's Fury",
            "Skull of the Titan",
            "Fortification Shield",
            "The Twisted Axe",
            "Blades of Denial",
            "Eidolon Toxin",
            "Glaive of Victory",
            "Victorious Banner",
            "Victorious Armor",
            "Necklace of Victory",
            "Huffy Hat",
            "Frozen Chestguard",
            "Told Before Time",
            "Hill Giant Club",
            "Earthforce Dice",
            "Inferno of Truth",
            "Blood-Fang",
            "Banner of Immense Protection",
            "Lance of Immense Protection",
            "Infused Katana",
            "Uber Sword",
            "Uber Armor",
            "Draketail Blade",
            "Quiver of the Chosen",
            "Chosen Armor",
            "Chosen Bow",
            "Crashing Crescendo",
            "Robe of the Gargoyle Summoner",
            "Speedier Sprout",
            "Purification Crystal",
            "Phantom Talisman",
            "Demonic Resonance",
            "Zol Elixir",
            "Bloodstone of Enmity",
            "Malgoric Skull",
            "Bone Axe",
            "Malgoric Charm",
            "Cloak of Vivacity",
            "Seal of Sky Serenade",
            "Omniarmor",
            "Omnihelm",
            "Raptor Ring",
            "Blazed Bow",
            "Shade of the Phoenix",
            "Blade of the Angel's Honor",
            "Poseidon's Gauntlet",
            "Alikyr the Alien King's Lance",
            "Wand of Parallel Distortion",
            "Shield of Infinity",
            "Spell of the Rah'",
            "Poor People Crown",
            "The Divine Protection",
            "Sanctum Key",
            "Bow of Ancient Carnage",
            "Blade of Sinister Deeds",
            "Bloodlust Katana",
            "Malice of Corrupt Souls",
            "Serial's Cloth of Gore",
            "Tyrant's Bloodplate",
            "Robe of Insidious Possession",
            "Helm of the Dark Legion",
            "Tome of Unstable Magic",
            "Skull of Demonic Grasp",
            "Bloodclot Poison",
            "Scepter of Blood Magic",
            "Seal of the Cursed Barbarian",
            "Prism of Demonic Illusions",
            "Shield of Hell's Armageddon",
            "Demoncatcher Trap",
            "Quiver of the Evil Undead",
            "Spell of Annihilation",
            "Reaper's Cloak",
            "Sword of the Frog Bearer",
            "Black Flame Staff",
            "Shield of Mucus",
            "Hellfire Orb",
            "Staff of Violent Mayhem",
            "Lightning and Thunder",
            "Starlight's Demise",
            "Coconut Orb1",
            "Lifesaver",
            "Staff of the Tidal Waves",
            "Heart of the Sea",
            "Verdant Spear",
            "Coconut Orb2",
            "Subspace Slasher",
            "Cry of the Lost Galaxies",
            "Nanotech Charm",
            "Quasar Hide",
            "Cosmic Platemail",
            "Contaminated Ring",
            "Strike of Calamity",
            "The Grand Grimoire",
            "Robe of the Celestial Grace",
            "Ring of Dwelling Nightmares",
            "Turkey Meal",
            "Wand of the Pilgrimage",
            "The Grand Feast",
            "Pilgrim's Robes",
            "The Cornucopia",
            "Bow of Disgust",
            "Champion's Arena Key",
            "Admin Dagger",
            "Admin Wand",
            "Admin Bow",
            "Admin Katana",
            "Wand of the Fallen",
            "Kageboshi"
        };
    }
}
